# Generated by Django 4.1.4 on 2022-12-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_unverifiedusers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unverifiedusers',
            old_name='code',
            new_name='kod',
        ),
    ]
