# Generated by Django 4.1.4 on 2022-12-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_code_unverifiedusers_kod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='debt',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='qarzi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='discard',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Discount karta'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ginfo',
            field=models.TextField(blank=True, null=True, verbose_name="Umumiy ma'lumot"),
        ),
    ]
