# Generated by Django 4.1.4 on 2022-12-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kod',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
